# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: ExtensionReleaseVersion
  value: $(Build.BuildNumber)
  
steps:
- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'npm install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run package'
  displayName: 'npm package'
- task: ReplaceTokens@1
  inputs:
    sourcePath: 
    filePattern: 'vss-extension.json'
    tokenRegex: '__(\w+)__'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cat vss-extension.json'
  displayName: 'cat vss-extension.json'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo npm install -g tfx-cli'
  displayName: 'install tfx'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'tfx extension publish --manifest-globs vss-extension.json --overrides-file configs/release.json -t $(extensionToken)'
  displayName: 'deploy'

